### ISSUE TITLE
Outputs for Pull zone

### ISSUE THREAD

**Issue by spaceemotion** [BunnyWay/terraform-provider-bunnynet#10]
We're trying to integrate some values from a BunnyCDN pullzone into other services:
1. The hostname (xyz.b-cdn.net)
2. The secret signing key

I'd like to forward both values to our backend, so we can generate the proper, signed URLs.

Is there a way to access them via the terraform resource outputs? I couldn't find them on the documentation page.

Thanks in advance.

**Comment by rafael-at-bunny** [comment]
Hi!

> 1. The hostname (xyz.b-cdn.net)

You can use `value = "${bunnynet_pullzone.test.name}.${bunnynet_pullzone.test.cdn_domain}"` to reference the pullzone's hostname. If you want to import the `bunnynet_pullzone_hostname` resource, see the example in https://github.com/BunnyWay/terraform-provider-bunnynet/issues/7#issuecomment-2321610095

> 2. The secret signing key

Do you mean the `Url Token Authentication Key` under Security > Token Authentication on dash.bunny.net?

<img width="972" alt="Screenshot 2024-09-09 at 09 44 36" src="https://github.com/user-attachments/assets/4d6928b0-c9f3-40eb-86d8-19237b82afc0">

This is available in terraform as [`token_auth_key`](https://registry.terraform.io/providers/BunnyWay/bunnynet/latest/docs/resources/pullzone#token_auth_key).

Thank you.
