### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by artema** [BunnyWay/terraform-provider-bunnynet#11]
Using any string values (`aspectRatio`, `autoOptimize`) of `PullzoneOptimizerClass` results in the following error:

```
Error: Provider produced inconsistent result after apply
         │ 
         │ When applying changes to
         │ bunnynet_pullzone_optimizer_class.bunny-pullzone-optimizer-class-filetiny,
         │ provider "provider[\"registry.terraform.io/bunnyway/bunnynet\"]" produced
         │ an unexpected new value: .aspect_ratio: was cty.StringVal("1:1"), but now
         │ cty.StringVal("\"1:1\"").
```

The value applied is also invalid (should be unquoted):

![Screenshot 2024-09-08 at 1 55 09 PM](https://github.com/user-attachments/assets/4e61bf84-45bb-43ce-9ca7-3d876d9b8b7c)

Provider version: 0.3.12

**Comment by rafael-at-bunny** [comment]
Hi!

It was indeed wrong. A fix has been released on v0.3.13.

Thank you.
