### ISSUE TITLE
Support for edge rule with multiple actions

### ISSUE THREAD

**Issue by PHameete** [BunnyWay/terraform-provider-bunnynet#13]
Hi there! 

I'm converting our BunnyCDN config into Terraform and run into the following issue: 

It seems that the `bunnynet_pullzone_edgerule` resource only allows a single action with 2 parameters, however the UI allows defining multiple actions on a single edge rule. 

Is this intentional, or will the resource be updated eventually to allow multiple actions?

And what is the current suggested approach to model such edge rules? Would it be to split an edge rule with multiple actions into multiple edge rules with a single action?

Thank you in advance!

**Comment by rafael-at-bunny** [comment]
Hi!

I've released the multi-actions support on v0.3.15.

Example:

```terraform
resource "bunnynet_pullzone_edgerule" "block_admin" {
  enabled     = true
  pullzone    = bunnynet_pullzone.wordpress.id
  description = "Block Admin"

  actions = [
    {
      type = "SetResponseHeader"
      parameter1 = "X-Reason"
      parameter2 = "unauthorized"
    },
    {
      type = "BlockRequest"
      parameter1 = null
      parameter2 = null
    },
  ]

  match_type = "MatchAny"
  triggers = [
    {
      type       = "Url"
      match_type = "MatchAny"
      patterns   = ["*/wp-admin/*"]
      parameter1 = null
      parameter2 = null
    },
  ]
}
```

You can still define `action` in the resource root, but you can't have both `action` and `actions` in the same resource.

Thank you.

**Comment by PHameete** [comment]
Thank you Rafael! I will try to use that today to refactor the edge rules and let you know if it went well 👍 !

**Comment by PHameete** [comment]
All worked well Rafael, thank you for the fast action!
