### ISSUE TITLE
attribute cdn_domain of bunnynet_pullzone is not complete

### ISSUE THREAD

**Issue by cecedille1** [BunnyWay/terraform-provider-bunnynet#16]
The `cdn_domain` attribute of a resource `bunnynet_pullzone` is `b-cdn.net` and that works nicely to create CNAME records. But it could be `<name>.b-cdn.net` and this name would resolve in ipv6. 

Can you add the whole name in the output of the resource please

**Comment by rafael-at-bunny** [comment]
Hi.

Currently you can concatenate `name` and `cdn_domain` to obtain the complete hostname. i.e.:

```terraform
output "pullzone_hostname" {
    value = "${bunnynet_pullzone.test.name}.${bunnynet_pullzone.test.cdn_domain}"
}
```

You can also use the snippet at #12 to manage this hostname (i.e.: configure SSL). We're currently passing through the `CnameDomain` field from the [bunny.net API](https://docs.bunny.net/reference/pullzonepublic_index2). Unfortunately that would be a breaking change.

Regarding IPv6, we currently do support IPv6 on `b-cdn.net` hostnames. If you are having troubles with it I suggest you to [contact the support team](https://bunny.net/contact/) directly.

Thank you.
