### ISSUE TITLE
`bunnynet_dns_record` - cannot set `name` to `@`

### ISSUE THREAD

**Issue by cschmatzler** [BunnyWay/terraform-provider-bunnynet#3]
Hi!

When trying to set an apex DNS record, applying the changes fails with

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to bunnynet_dns_record.a_frontend, provider "provider[\"registry.terraform.io/bunnyway/bunnynet\"]" produced an unexpected new value: .name: was cty.StringVal("@"), but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
````

## Reproduction

```
resource "bunnynet_dns_record" "a_frontend" {
  zone = bunnynet_dns_zone.leuchtturm.id

  name         = "@"
  type         = "A"
  value        = module.frontend_nodes[0].ipv4
  monitor_type = "Http"
}
```

This is fixed by setting `name` to `""`, but I would expect `@` to be accepted as well. Especially since the API call to bunny succeeds and the record is created correctly.

**Comment by rafael-at-bunny** [comment]
Hi!

I don't see a good way to support `@`, as the API will return an empty string regardless of how you set it. From my tests, this can make the record to be re-created on every apply.

I did however changed the documentation, so it's clear how to set an apex domain record: 8ffd3a63d51c9f53200a1b90921dbebbcf22ca8b

Thank you for the report!
