### ISSUE TITLE
Issue. resource bunnynet_pullzone_hostname

### ISSUE THREAD

**Issue by AndreiPaulau** [BunnyWay/terraform-provider-bunnynet#7]
Hello,

I'm facing the issue with following resources:

```
resource "bunnynet_pullzone_hostname" "bunnynet" {
  pullzone    = bunnynet_pullzone.wasm.id
  name        = "${local.name}-${local.environment}-${local.domain}.b-cdn.net"
  tls_enabled = true
  force_ssl   = true
}

resource "bunnynet_pullzone_hostname" "custom" {
  pullzone    = bunnynet_pullzone.wasm.id
  name        = local.environment == "production" ? "${local.name}.${local.domain}.com" : "${local.name}-${local.environment}-${local.domain}.com"
  tls_enabled = true
  force_ssl   = true
}
```

```
 Error: Unable to create hostname
│ 
│   with module.wasm_bunny_cdn.bunnynet_pullzone_hostname.bunnynet,
│   on ../../modules/bunny-wasm/main.tf line 55, in resource "bunnynet_pullzone_hostname" "bunnynet":
│   55: resource "bunnynet_pullzone_hostname" "bunnynet" {
│ 
│ addHostname failed with 400 Bad Request
╵
╷
│ Error: Unable to create hostname
│ 
│   with module.wasm_bunny_cdn.bunnynet_pullzone_hostname.custom,
│   on ../../modules/bunny-wasm/main.tf line 62, in resource "bunnynet_pullzone_hostname" "custom":
│   62: resource "bunnynet_pullzone_hostname" "custom" {
│ 
│ addHostname failed with 400 Bad Request
```

disable_letsencrypt = true
if in ```false``` - loadFreeCertificate failed with 400 Bad Request error occurs

moreover, would be great to have a resource related to custom certificate upload and linking it to bunnynet_pullzone_hostname resource

Just in case - there is a separate ticket 274243

Thanks!

**Comment by AndreiPaulau** [comment]
Just in case, I see in the UI Under "CDN -> Hostanmes -> Linked Hostnames" the records I tried to create, but they are not in terraform state (Simply because all the api calls were successful) The behavior should be reviewed as well, since when the records will be resolved, I believe the terraform will error since the resource with such name are exists.

Ok, what about resource "bunnynet_pullzone_hostname" "bunnynet"? (It's b-cdn.net)

And the last
We didn't onboard our domain under bunny.net since we'd like to host it as is.
Did I get you right, as soon as we Create record on our domain provider and it will be resolved - the operation will be successful?

Thanks!

**Comment by rafael-at-bunny** [comment]
Hi!

> The behavior should be reviewed as well

Indeed, I'll investigate how that can be done.

--

> Ok, what about resource "bunnynet_pullzone_hostname" "bunnynet"? (It's b-cdn.net)

You can import the `<pullzoneName>.b-cdn.net` hostname with the following configuration:

```terraform
resource "bunnynet_pullzone_hostname" "hostname_bcdn" {
  pullzone = bunnynet_pullzone.mypz.id
  name = "${bunnynet_pullzone.mypz.name}.b-cdn.net"
}

import {
  id = "${bunnynet_pullzone.mypz.id}|${bunnynet_pullzone.mypz.name}.b-cdn.net"
  to = bunnynet_pullzone_hostname.hostname_bcdn
}
```

However, that might not work if you are trying to do it in a single pass. See https://github.com/BunnyWay/terraform-provider-bunnynet/issues/5#issuecomment-2317646084

--

> as soon as we Create record on our domain provider and it will be resolved - the operation will be successful?

The DNS record is needed to perform the domain validation to obtain the certificate. The record must exist before adding the hostname to the pullzone. If you add your custom domain via the UI, it will tell you to configure the CNAME first:

<img width="464" src="https://github.com/user-attachments/assets/142da293-fe5b-4c32-9d94-fcc57b8e6149">


Adding a hostname via Terraform has the same requirement. You have to make sure the DNS record exists before the `bunnynet_pullzone_hostname` is processed. You can achieve that with depends_on, but if you manage the DNS outside terraform, you'll have to do that before running `terraform apply`.

Thank you.

**Comment by rafael-at-bunny** [comment]
Hi @AndreiPaulau.

Custom certificates support was released on v0.3.11. The [example usage](https://registry.terraform.io/providers/BunnyWay/bunnynet/latest/docs/resources/pullzone_hostname#example-usage) was also updated.

Hostnames with custom certificates can also be imported, however, because the API does not return the existing certificates, it will override them on apply. Make sure you're defining the correct before applying.

Thank you!

**Comment by AndreiPaulau** [comment]
Oh my! Super!

Thank you for the quick response!

One more proposal regarding bunnynet_pullzone_hostname resource.
Just an assumption...
At the UI, as you posted earlier, there is a "skip verify" button, may be this is possible solution?

verify_cname = true (default), which would force cname verification api call, and if false, won't do that and will successfully onboard resource into terraform state.

**Comment by rafael-at-bunny** [comment]
Hi.

The `skip verify` button will add the hostname, but without a TLS certificate. It would be the same as adding the hostname with `tls_enabled = false`.

Thank you.
