### ISSUE TITLE
custom_404_file_path error

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [BunnyWay/terraform-provider-bunnynet#8]
I can't nullify the `custom_404_file_path` of a storage zone:
```terraform
    resource "bunnynet_storage_zone" "permanent-logs" {
      name      = "permanent-logs-staging"
      region    = "NY"
      zone_tier = "Standard"
      custom_404_file_path = null
    }
```

plans shows
```terraform
  # bunnynet_storage_zone.permanent-logs will be updated in-place
  ~ resource "bunnynet_storage_zone" "permanent-logs" {
      - custom_404_file_path = "/404.html" -> null
      ~ date_modified        = "2024-09-04T09:46:33" -> (known after apply)
        id                   = ....
        name                 = "permanent-logs-staging"
        # (6 unchanged attributes hidden)
    }
```
but apply fails:
```bash
bunnynet_storage_zone.permanent-logs: Modifying... [name=permanent-logs-staging]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to bunnynet_storage_zone.permanent-logs, provider "provider[\"registry.terraform.io/bunnyway/bunnynet\"]" produced an unexpected new value: .custom_404_file_path: was null, but now cty.StringVal("/404.html").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

The resource was initially imported using `terraform import`

**Comment by rafael-at-bunny** [comment]
Hi.

Our API team fixed the underlying issue and `custom_404_file_path` can now be unset. Please upgrade the provider to v0.3.12 (just released).

Thank you.

**Comment by pwilczynskiclearcode** [comment]
@rafael-at-bunny Thank you.

What about `.triggers[0].parameter1` and `.triggers[0].parameter2` of the edge rules that [I mentioned](https://github.com/BunnyWay/terraform-provider-bunnynet/issues/8#issuecomment-2328450959). Why they are always required fields when in many edge rules they must be `null`. What is [this error message](https://github.com/BunnyWay/terraform-provider-bunnynet/issues/8#issuecomment-2328450959) about? Is it possible that provider sends `""` (empty string) but API returns `null` so terraform complains?

**Comment by rafael-at-bunny** [comment]
Hi.

> Why they are always required fields when in many edge rules they must be null

That's unfortunately a limitation in the terraform framework (see https://github.com/hashicorp/terraform-plugin-framework/issues/726), as we can't define defaults (or even `Required: false`) on nested attributes.

> What is https://github.com/BunnyWay/terraform-provider-bunnynet/issues/8#issuecomment-2328450959 about?

I'd need more details (as in: the terraform resource that caused it). We are handling empty strings for those attributes, so I'm not sure how you're triggering this error.

https://github.com/BunnyWay/terraform-provider-bunnynet/blob/90ba83d93fc02e6a31d98bccf80054516ee63c61/internal/provider/resource_pullzone_edgerule.go#L405-L410

Thank you.

**Comment by pwilczynskiclearcode** [comment]
Sorry I can't reproduce it. I believe that was related somehow to using `terraform import bunnynet_pullzone_edgerule...` but it works now.
Thank you for the help
